name = "blaze-it-backend"
main = "./worker.ts"
compatibility_date = "2024-10-29"

assets = { directory = "../frontend/dist" }

[[d1_databases]]
binding = "DB"
database_name = "blaze-it-db"
database_id = "your-database-id-here"

[vars]
# Placeholders; set via wrangler or dashboard
APP_ID = ""
DEV_PORTAL_API_KEY = ""
TOKEN_FACTORY_ADDRESS = ""
TREASURY_ADDRESS = ""

[observability]
enabled = true
