name = "blaze-it-backend"
main = "./worker.ts"
compatibility_date = "2024-10-29"

assets = { directory = "../frontend/dist" }

[vars]
# Placeholders; set via wrangler or dashboard
APP_ID = ""
DEV_PORTAL_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
TOKEN_FACTORY_ADDRESS = ""
TREASURY_ADDRESS = ""

[observability]
enabled = true
